name: goldyu
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ^3.5.4


#------------- Packages -------------#
dependencies:
  flutter:
    sdk: flutter

  # Core packages
  http: ^1.2.2
  dio: ^5.7.0
  intl: ^0.20.1
  logger: ^2.5.0
  url_launcher: ^6.3.1


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management 
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3

  #other packages
  lottie: ^3.2.0
  flutter_secure_storage: ^9.2.4






#------------- ./Packages End -------------#

#------------- Dev Packages -------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#------------- ./Dev Packages End -------------#


flutter:
  uses-material-design: true

  #-------------- Local assets --------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/animations/

  #-------------- Local Fonts --------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800

